name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # يعمل يوميًا
  push:
    branches: [main]
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: faresFatooh
          outputs: |
            output/snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
